main: me.Blume.BlumesCompass.Main
name: BlumesCompass
author: Blume
version: 1.0
api-version: 1.16

commands:
  hunt:
    description: hunters use this code to hunt speedrunner
  removehunt:
    description: If you stopped hunting hunter should use this code to remove compass
  
  